#--------------------------------------------------
#
#
#--------------------------------------------------

name: My-GitHub-Action-Basics

on:
  push:
    branches:
      - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hellow Message From Testing
      run : echo "Hellow World from Testing job"


  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
    
    steps:
    - name: Print Hellow Message From Deploy
      run : echo "Hellow World Deploy job"

  
